### ISSUE TITLE
travis build broken because of go/logx

### ISSUE THREAD

**Issue by yachang** [m-lab/go#103]
github.com/m-lab/go/logx
# github.com/m-lab/go/logx
../go/logx/logx.go:40:19: logger.Writer undefined (type *log.Logger has no field or method Writer)
github.com/m-lab/etl/etl
github.com/m-lab/go/bqx
The command "go get -v -t ./..." failed and exited with 2 during .

**Comment by mehtab11** [comment]
@yachang - Pls. Upgrade the go version.

**Comment by yachang** [comment]
Fixed.
