### ISSUE TITLE
Tests are flaky

### ISSUE THREAD

**Issue by pboothe** [m-lab/go#65]
`logx` fails when weird things happen with task scheduling on Travis.
`bqext` fails every now and then for reasons I have not investigated.

It's frustrating, and I wish the associated tests were more reliable.

**Comment by stephen-soltesz** [comment]
Apparently caused by an upstream change to error string contents in `bigquery` package for the bqfake_test errors.

The memoryless_test errors due to a race in the unit test.

Fixed by https://github.com/m-lab/go/pull/69

**Comment by stephen-soltesz** [comment]
https://github.com/m-lab/go/pull/72
