### ISSUE TITLE
Migrate clients off go/bqx to go/cloud/bqx.

### ISSUE THREAD

**Issue by gfr10598** [m-lab/go#99]
Also see #88 

bqx should be grouped with the cloud packages.  There is now a copy in go/cloud/bqx, and clients should migrate to that path.

./go/cloud/bqx/schema_test.go:21:
./etl-gardener/job-service/job-service_test.go:19:
./etl-gardener/tracker/tracker_race_test.go:16:
./etl-gardener/tracker/tracker.go:30:
./etl-gardener/tracker/tracker_test.go:14:
./etl-gardener/tracker/handler_test.go:16:
./etl-gardener/ops/ops_test.go:10:
./etl-gardener/ops/actions_test.go:13:
./etl/cmd/generate_schema_docs/main.go:32:
./etl/cmd/update-schema/update.go:25:
./etl/parser/ndt_result.go:50://
./etl/schema/schema_test.go:9:
./etl/schema/ndt_result_test.go:7:
./etl/schema/schema.go:10:
./etl/schema/tcpinfo.go:10:
./etl/schema/pt_schema.go:10:
./etl/schema/ndt_result.go:5:

**Comment by stephen-soltesz** [comment]
Obsolete.
